exercises/hamming/hamming_test.sh

Also added a couple of tests to avoid this.

Fix hamming test containing invalid DNA letters

---

config.json
exercises/gigasecond/example.sh
exercises/gigasecond/gigasecond_test.sh
exercises/rna-transcription/example.sh
exercises/rna-transcription/rna_transcription_test.sh

Added the Gigasecond and RNA Transcription exercises, copying the test cases from the Ruby versions of these problems.

Added Gigasecond and Rna Transcription exercises.

---

config.json
exercises/raindrops/example.sh
exercises/raindrops/raindrops_test.sh

Based on Ruby, Php, Rust versions

Add raindrops exercise

---

exercises/leap/example.sh

Make usage into a function
This outputs to stderr and avoid repeating exit(1)

Better leap example: DRY up displaying error

---

config.json
exercises/bob/bob_test.sh
exercises/bob/example.sh

I used the python version as a base for this.

Add bob exercise

---

config.json

This should cover step 1 of https://github.com/exercism/xbash/issues/24

Add exercise key to config.json

---

exercises/hello-world/hello_world_test.sh

This removes the intermediate exercises from hello-world as suggested in #29.

Remove intermediate exercises from hello-world

---

docs/TESTS.md
exercises/bob/bob_test.sh
exercises/gigasecond/gigasecond_test.sh
exercises/hamming/hamming_test.sh
exercises/hello-world/hello_world_test.sh
exercises/leap/leap_test.sh
exercises/raindrops/raindrops_test.sh
exercises/rna-transcription/rna_transcription_test.sh

I added shebangs for simple run bats files

Add shebang for bats files and change file permission for simple run tests

---

config.json

Follow-up to https://github.com/exercism/discussions/issues/159

Delete active key from config

---

config.json
exercises/hello-world/example.sh
exercises/hello-world/hello_world_test.sh
exercises/two-fer/example.sh
exercises/two-fer/two_fer_test.sh

Add two-fer to track and update hello-world to match canonical data

two-fer: add to track

---

config.json
exercises/phone-number/example.sh
exercises/phone-number/phone_number_tests.sh

Created phone_number_test.sh and example.sh and updated config.json with this problem.  Let me know if I should fix anything!

Implementing "phone-number" exercise

---

config.json
config/maintainers.json
exercises/error-handling/error_handling_test.sh
exercises/error-handling/example.sh

Currently only has argument checking

Error handling exersise #47

---

docs/ABOUT.md

About Bash.  Just a blurb, can be expanded.
exercism/meta#85

Introducing Bash

---

config.json
exercises/word-count/example.sh
exercises/word-count/word_count_test.sh

Resolves #77 
I've ported the tests from [`canonical-data.json`](https://github.com/exercism/problem-specifications/blob/master/exercises/word-count/canonical-data.json) for the exercise, but I didn't have a chance to run them locally.
I've never written unit tests for bash scripts, so there could be mistakes. I'll check everything tomorrow
Feedback is always welcomed! 🤝

Adds test suite for word-count

---

config.json
config/maintainers.json

This runs configlet fmt against the track config and maintainer config files.
FYI @kotp @kenden @Smarticles101 @nywilken - I noticed #83 has some formatting changes unrelated to the fix, so I wanted to get the formatting sorted out separately.

Normalize config files

---

config.json

Add language attribute to config.json

---

config.json

Revert "Add language attribute to config.json"

---

config.json
exercises/atbash-cipher/README.md
exercises/atbash-cipher/atbash_cipher_tests.sh
exercises/atbash-cipher/example.sh

Implementation of atbash cipher for the bash language stream.

Bash atbash cipher patch

---

exercises/gigasecond/.meta/hints.md
exercises/two-fer/README.md

Fix contents of README based on order. Add .meta/hints.md to gigasecond.

---

config.json
exercises/triangle/README.md
exercises/triangle/example.sh
exercises/triangle/triangle_test.sh

Finish first draft of README
Finish initial test generation
Update tests with skips, fix typos
Create example script
Update config.json with triangle problem data

Implement Triangle Exercise

---

config.json
exercises/acronym/README.md
exercises/acronym/acronym.sh
exercises/acronym/acronym_tests.sh
exercises/acronym/example.sh

Adding my first programming exercise to exercism.io.

Add an acronym exercise for the bash language in exercism.io

---

config.json
exercises/armstrong-numbers/README.md
exercises/armstrong-numbers/armstrong_numbers_test.sh
exercises/armstrong-numbers/example.sh

Add the armstrong-numbers exercise to track as per [exercism/problem-specifications/issues/1017](https://github.com/exercism/problem-specifications/issues/1017)

armstrong-numbers: add to track

---

config.json

I noticed that the final exercise was only rated as a 2 - maybe it was just appended?
Re-ordered in difficulty order.

reorder config by difficulty

---

config/maintainers.json

Added myself to list of maintainers

config/maintainers: add sjwarner-bp to maintainers.json

---

config.json

fix invalid uuids

---

config.json
exercises/reverse-string/README.md
exercises/reverse-string/example.sh
exercises/reverse-string/reverse_string_test.sh

Add reverse-string to bash track as per [todo](http://exercism.io/languages/bash/todo)

reverse-string: add to track

---

config.json
exercises/roman-numerals/README.md
exercises/roman-numerals/example.sh
exercises/roman-numerals/roman_numerals_test.sh

Add roman-numerals to bash track as per [todo](http://exercism.io/languages/bash/todo)

roman-numerals: add to track

---

CONTRIBUTING.md

contributing: document where hints.md should be kept.

---

exercises/triangle/triangle_test.sh

Fixes the `triangle_test.sh` bats shebang.

triangle: fix test shebang

---

exercises/acronym/example.sh
exercises/anagram/example.sh
exercises/armstrong-numbers/example.sh
exercises/atbash-cipher/example.sh
exercises/bob/example.sh
exercises/error-handling/example.sh
exercises/gigasecond/example.sh
exercises/hamming/example.sh
exercises/hello-world/example.sh
exercises/leap/example.sh
exercises/nucleotide-count/example.sh
exercises/pangram/example.sh
exercises/raindrops/example.sh
exercises/reverse-string/example.sh
exercises/rna-transcription/example.sh
exercises/roman-numerals/example.sh
exercises/triangle/example.sh
exercises/two-fer/example.sh
exercises/word-count/example.sh

As we move towards preferring the user's path to locate `bash` (#123, #121), I've updated the existing exercises with this change.
Let me know what you think about this 👍

add #!/usr/bin/env bash shebang

---

config.json
exercises/grains/README.md
exercises/grains/example.sh
exercises/grains/grains_test.sh

grains: add to track

---

config.json
exercises/collatz-conjecture/README.md
exercises/collatz-conjecture/collatz_test.sh
exercises/collatz-conjecture/example.sh

Add to track as part of fleshing out track, in preparation for launch.
I've not put the logic in a function - I figured that this should be ok, but let me know what you think!

collatz-conjecture: add to track

---

config.json
exercises/luhn/README.md
exercises/luhn/example.sh
exercises/luhn/luhn_test.sh

As part of fleshing out the track, I've added `luhn`.
I need to fix the conflict, but once someone has approved it then I'll fix that in the web-editor and merge in 🙂

luhn: add to track

---

CONTRIBUTING.md

I was reading the contributing document in the terminal, and found that the lines would wrap at inconvenient places in the terminal.

Formatting so that it reads well in terminal

---

config/exercise_readme.go.tmpl
docs/EXERCISE_README_INSERT.md
exercises/acronym/README.md
exercises/anagram/README.md
exercises/armstrong-numbers/README.md
exercises/atbash-cipher/README.md
exercises/bob/README.md
exercises/collatz-conjecture/README.md
exercises/difference-of-squares/README.md
exercises/error-handling/README.md
exercises/gigasecond/.meta/hints.md
exercises/gigasecond/README.md
exercises/grains/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/leap/README.md
exercises/luhn/README.md
exercises/nucleotide-count/README.md
exercises/pangram/README.md
exercises/phone-number/README.md
exercises/raindrops/README.md
exercises/reverse-string/README.md
exercises/rna-transcription/README.md
exercises/roman-numerals/README.md
exercises/triangle/README.md
exercises/two-fer/README.md
exercises/word-count/README.md

Fixes #138. This consists of:
* update exercise_readme.go.tmpl with better test command
* regenerate readmes (update content and change test command)
* remove unused EXERCISE_README_INSERT
Basically, I moved the 'test' section into the template and out of the insert, and used the snake case exercise variable to automate the generation of the test command. This was done manually in #131 and #130.
After that, I regenerated READMEs using the recommended configlet method. This has pulled in recent changes from problem specifications.
I think this is the best way to automate and manage READMEs in future.

Automate README test commands

---

CONTRIBUTING.md

[As mentioned](https://github.com/exercism/bash/issues/138#issuecomment-355826740) in #138.

Style guide for bash

---

.travis.yml
bin/validate-exercises

Fixes: #148 
OSX was adde as a target system, but I had to wait 10 minutes and a build was not started, it's probably not worth the wait since probably resources for OS are scarce.
I need to wait until all the other PR are merged before merging this one, and then fixing the commits and squashing.

Add Travis check for exercises

---

exercises/reverse-string/example.sh
exercises/reverse-string/reverse_string_test.sh

I have updated the first test to send an empty string instead of no argument, since they are different.
Good first PR to check the new CI integration as well.

[reverse-string] Update test to follow specification

---

config.json

I would even argue it's a difficulty 3 exercise since you have to deal with overflow in bash.

Update grains difficulty

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a pull request template to fix #157 
This should allow our policies to be more easily accessible / more often adhered to.

add PR template with link to POLICIES document

---

config.json

More accurate difficulty for roman-numerals.

Updated roman-numerals difficulty

---

exercises/hello-world/hello_world.sh

updates a hello_world.sh comment

---

config.json

Add blurb to the `config.json` as part of #168
---

add blurb to config for nextercism

---

config.json

Add auto_approve: true to hello-world config as part of #168 
---

add auto_approve: true to hello-world config

---

config.json

Activate bash track, since we have everything we need for the launch.
#168

Activate track

---

exercises/leap/leap_test.sh
exercises/word-count/word_count_test.sh

leap;word-count: Replaced test run command with 'run bash' in the test suites

---

scripts/canonical_data_check.sh

I tried to make the comments succinct.  Let me know if you all think there should be any changes to the comments.
closes #181 
---

commented jq invocations in scripts/canincal_data_check.sh

---

POLICIES.md

Fixed small typo in POLICIES.md

---

config/exercise_readme.go.tmpl
exercises/acronym/README.md
exercises/anagram/README.md
exercises/armstrong-numbers/README.md
exercises/atbash-cipher/README.md
exercises/bob/README.md
exercises/collatz-conjecture/README.md
exercises/difference-of-squares/README.md
exercises/error-handling/README.md
exercises/gigasecond/README.md
exercises/grains/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/leap/README.md
exercises/luhn/README.md
exercises/nucleotide-count/README.md
exercises/pangram/README.md
exercises/phone-number/README.md
exercises/raindrops/README.md
exercises/reverse-string/README.md
exercises/rna-transcription/README.md
exercises/roman-numerals/README.md
exercises/scrabble-score/README.md
exercises/triangle/README.md
exercises/two-fer/README.md
exercises/word-count/README.md

This PR updates the existing READMEs and closes  #204.
When I regenerated READMEs via `configlet`, several exercises got an updated README from the latest `problem-specification`. 
For this PR I have excluded those changes, and left only my own. 
Should I update exercises with latest `problem-specification` in this or separate PR?
---

Added POSIX compliance section to the README

---

exercises/armstrong-numbers/README.md
exercises/bob/README.md
exercises/hamming/README.md
exercises/rna-transcription/README.md
exercises/two-fer/README.md

Updated READMEs of the exercises according to the latest problem-specification  

---

exercises/hello-world/.meta/hints.md

hello-world: Fixed typo in hints

---

_template/README.md

Fixed typo in _template.README.md

---

config/maintainers.json

Hey,
Thanks for suggesting that I become a maintainer @budmc29.
I appreciate everyone else's work, and I look forward to continuing participation in the development and maintenance of this track.
Thanks,
Guy Gastineau
PS. Let me know if there is anything else I need to do for this.
---

Add myself as a maintainer

---

exercises/hello-world/hello_world.sh

Add note for starting template since I see many students just copying and pasting as it is.
@exercism/bash

Update starting template

---

exercises/acronym/acronym_test.sh
exercises/affine-cipher/affine_cipher_test.sh
exercises/anagram/anagram_test.sh
exercises/armstrong-numbers/armstrong_numbers_test.sh
exercises/atbash-cipher/atbash_cipher_test.sh
exercises/bob/bob_test.sh
exercises/collatz-conjecture/collatz_conjecture_test.sh
exercises/diamond/diamond_test.sh
exercises/difference-of-squares/difference_of_squares_test.sh
exercises/error-handling/error_handling_test.sh
exercises/gigasecond/gigasecond_test.sh
exercises/grains/grains_test.sh
exercises/hamming/hamming_test.sh
exercises/hello-world/hello_world_test.sh
exercises/isogram/isogram_test.sh
exercises/leap/leap_test.sh
exercises/luhn/luhn_test.sh
exercises/nucleotide-count/nucleotide_count_test.sh
exercises/pangram/pangram_test.sh
exercises/phone-number/phone_number_test.sh
exercises/raindrops/raindrops_test.sh
exercises/reverse-string/reverse_string_test.sh
exercises/rna-transcription/rna_transcription_test.sh
exercises/roman-numerals/roman_numerals_test.sh
exercises/scrabble-score/scrabble_score_test.sh
exercises/triangle/triangle_test.sh
exercises/two-fer/two_fer_test.sh
exercises/word-count/word_count_test.sh

Change 'bats' shebang to 'bash'

---

config.json

config.json: Removed the 'stdout' tag

---

config.json

nucleotide_count: Made the exercise to be unlocked by the 'hamming' exercise

---

config.json

This exercise's hard parts are definitely figuring out how to do math (and especially math with integers larger than the signed int limit).  Maybe even more so than control flow and input validation.  I thought it would be good to add them to the tags on this exercise.
---

Grains: Add "integers" and "math" tags.

---

docs/ABOUT.md

Just a minor typo I noticed when checking out the [about page for this track](https://exercism.io/my/tracks/bash).
---

ABOUT.md: fix minor typo

---

exercises/hello-world/README.md

There is nothing to skip in the hello world exercise, so the comment can
be confusing for someone first seeing it.
This adds the expectation for following exercises.
closes #273
---

Describe skips better, with anticipation

---

exercises/binary-search/binary_search_test.sh

forgot to add skips in the test suite

---

exercises/sieve/example.sh

I'm an unashamed tinkerer. I want to make the example solution as close as possible to the algorithm mostly so I can demonstrate the effectiveness of simple optimizations.
---

implement the sieve example as purely as possible to the algorithm

---

exercises/sieve/example.sh

I went too far with my last tweak to the sieve exercise. This fixes it.
---

correct the previous correction for sieve

---

exercises/two-fer/two_fer_test.sh

Tidy the two-fer test file.
---

Clean the test file: the skip search&replace was too aggressive.

---

config/exercise_readme.go.tmpl
docs/ABOUT.md
docs/INSTALLATION.md
docs/LEARNING.md

A note about the INSTALLATION.md changes: the `$SHELL` environment variable is set by the login system, and it contains your login shell as configured in /etc/passwd. It's not about what shell is currently running. For example
```
$ /bin/bash --login
$ echo $SHELL
/usr/local/bin/fish
```
I change that section to use the `$BASH_VERSION` shell variable instead.
---

Mostly just formatting the .md files for shorter lines.

---

docs/INSTALLATION.md

No need to have bash as the active shell, the goal is to write scripts, not environment settings.
---

Bash shell not required

---

config.json

bin/configlet lint lints the config.json

---

exercises/anagram/anagram_test.sh

double brackets for the new anagram tests

---

exercises/dnd-character/dnd_character_test.sh

Add a missing 'd' in 'expected'
---

Fix typo in dnd

---

config/maintainers.json

adding Glenn to the list of maintainers

---

mentor_tools/bantor

Added logging: it's not specific log messages, but (most) of the session is dumped into the log file.
I also moved some functions around which contributes to the bulk of the diff.
---

bantor: add logging

---

_template/exercise_stub

Attempting to avoid confusion for students regarding terminology in the stub file template `exercise-stub`.
---

remove mention of stub from exercise_stub

---

bin/fetch_configlet

fetch-configlet: new version as of 4 months ago
Hopefully this will solve the travis issue.
Here is the [commit](https://github.com/exercism/configlet/commit/c6324a79289af2bbe2c97c26497ae9293be5ce6c#diff-0cb166cee465745304f179d67aae27d4) that made the update to `exercism/configlet`.
---

fetch-configlet: Update to latest version

---

exercises/triangle/triangle_test.sh

The tests were not covering same cases of 'triangle inequality violation'
[canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json)
fixes #384
---

updated tests for triangle exercise

---

exercises/resistor-color-trio/resistor_color_trio_test.sh

added test case to Resistor Color Trio

---

docs/INSTALLATION.md

Plus, tweak the Linux wording a bit.
---

Expanding the list of alternatives for installing bash on Windows.

---

docs/INSTALLATION.md

Homebrew instructions for Mac.
This should not conflict with my other PR expanding Windows instructions.
---

expand Mac installation section

---

exercises/hamming/hamming_test.sh

Realized need for this test in a mentoring session.
---

hamming: add test to expose == as a pattern matching operator

---

exercises/hamming/hamming_test.sh

Slight tweak to make the test name appear correctly during a bats run.
---

hamming test suite: test name does not display correctly

---

exercises/markdown/markdown.sh

ref issue https://github.com/exercism/bash/issues/409
---

markdown exercise: pre-refactored code does not pass tests on OSX

---

config/maintainers.json

Bash maintainer entry for myself.
---

Add Bash maintainer entry for bkhl

---

config/maintainers.json

Going ahead and showing myself on the website, based on the comments on https://github.com/exercism/bash/pull/417
---

Show bkhl on web site

---

docs/RESOURCES.md

doc: link to podcast episode.

---

exercises/grep/.meta/hints.md
exercises/grep/README.md

README was regenerated using configlet
---

grep exercise: Let users know to use bash not grep. Provide hints.

---

config/maintainers.json

Add IsaacG to the maintainers

---

exercises/allergies/allergies_test.sh
exercises/armstrong-numbers/armstrong_numbers_test.sh
exercises/beer-song/beer_song_test.sh
exercises/crypto-square/crypto_square_test.sh
exercises/darts/darts_test.sh
exercises/difference-of-squares/difference_of_squares_test.sh
exercises/dnd-character/dnd_character_test.sh
exercises/error-handling/error_handling_test.sh
exercises/food-chain/food_chain_test.sh
exercises/hello-world/hello_world_test.sh
exercises/kindergarten-garden/kindergarten_garden_test.sh
exercises/knapsack/knapsack_test.sh
exercises/leap/leap_test.sh
exercises/meetup/meetup_test.sh
exercises/nth-prime/nth_prime_test.sh
exercises/ocr-numbers/ocr_numbers_test.sh
exercises/palindrome-products/palindrome_products_test.sh
exercises/poker/poker_test.sh
exercises/pythagorean-triplet/pythagorean_triplet_test.sh
exercises/queen-attack/queen_attack_test.sh
exercises/rail-fence-cipher/rail_fence_cipher_test.sh
exercises/rectangles/rectangles_test.sh
exercises/reverse-string/reverse_string_test.sh
exercises/robot-simulator/robot_simulator_test.sh
exercises/simple-cipher/simple_cipher_test.sh
exercises/sublist/sublist_test.sh
exercises/tournament/tournament_test.sh
exercises/transpose/transpose_test.sh
exercises/variable-length-quantity/variable_length_quantity_test.sh
exercises/wordy/wordy_test.sh

The test files got roughly 2k `[[ ==` and roughly 450 `[[ x =`.
Make that all-or-none :)
---

Consistently use == over = inside [[

---

exercises/house/house_test.sh

$  grep ' == \*".*"\*'  */*test.sh  | wc -l
82
$  grep ' == \*[^"]'  */*test.sh  | wc -l
4
---

Quote the RHS for the [[ x == *"y"* ]] as per all the other test code.

---

mentor_tools/bantor

And allow for configurable display.
I trimmed trailing whitespace, so the diff is a little larger than the actual changes.
---

bantor: show line numbers with code.

---

exercises/satellite/satellite_test.sh

Looks like I forgot to add the exercise version to the test file for the satellite exercise.
---

add exercise version to satellite test script

---

mentor_tools/bantor

This also allows `bantor https://exercism.io/mentor/solutions/<uuid>` which can save a few mouse clicks.
---

Simplify how I acquire the UUID from the cmdline args

---

docs/TESTS.md

Adding more emphasis to stay away from sstephenson/bats

---

config.json
exercises/square-root/.meta/tests.toml
exercises/square-root/README.md
exercises/square-root/example.sh
exercises/square-root/square_root.sh
exercises/square-root/square_root_test.sh

square-root: create exercise

---

bin/validate_one_exercise
exercises/acronym/example.sh

A review suggestion for #453, and a cosmetic exercise change to test PR CI

---

.github/scripts/pr
docs/TESTS.md

https://github.com/exercism/exercism/issues/5412
---

Add note about possibly having to checkout tag v1.1.0 for bats-core

---

bin/validate_exercises

This change will validate all exercises in `exercises/practice/` and in the future `exercises/concept/`  
Addresses issue #479 
---

look for exercises in all subdirectories of exercises/

---

POLICIES.md

Includes change:
is most import
is most important
---

Sentence per line consistency

---

config.json

Addresses issue #470 
Reviewers, refer to https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md#tags
---

Add tags to config.json

---

config.json
exercises/practice/list-ops/.meta/config.json

resulting from `bin/fetch_configlet && bin/configlet lint`
---

config file fixes for list-ops exercise

---

exercises/practice/list-ops/.meta/tests.toml

list-ops: this is a valid tests.toml file

---

exercises/practice/anagram/.meta/tests.toml
exercises/practice/anagram/anagram_test.sh
exercises/practice/change/.meta/example.sh
exercises/practice/change/.meta/tests.toml
exercises/practice/change/change_test.sh
exercises/practice/diffie-hellman/.meta/tests.toml
exercises/practice/diffie-hellman/diffie_hellman_test.sh
exercises/practice/forth/.meta/example.sh
exercises/practice/forth/.meta/tests.toml
exercises/practice/forth/forth_test.sh
exercises/practice/hamming/.meta/tests.toml
exercises/practice/hamming/hamming_test.sh
exercises/practice/isogram/.meta/tests.toml
exercises/practice/isogram/isogram_test.sh
exercises/practice/kindergarten-garden/.meta/tests.toml
exercises/practice/kindergarten-garden/kindergarten_garden_test.sh
exercises/practice/luhn/.meta/example.sh
exercises/practice/luhn/.meta/tests.toml
exercises/practice/luhn/luhn_test.sh
exercises/practice/prime-factors/.meta/tests.toml
exercises/practice/prime-factors/prime_factors_test.sh
exercises/practice/transpose/.meta/example.sh
exercises/practice/transpose/.meta/tests.toml
exercises/practice/transpose/transpose_test.sh

Bring tests suites up to date with current problem specifications.

Fill in missing test cases

---

exercises/practice/tournament/.meta/tests.toml
exercises/practice/tournament/tournament_test.sh

Tests numeric sorting and table alignment.

tournament: add new test

---

exercises/practice/hello-world/hello_world.sh

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

.github/workflows/ci.yml
.github/workflows/pr.yml

Update: testing tool bats no longer using node

---

exercises/practice/hello-world/.docs/instructions.md

I wasn't sure if this is a good idea or not, as other tracks don't have this. But again, other tracks have more established testing concepts.
Since this is a "hello world" exercise, it could be discouraging that there are no instructions.
I hope this has not been discussed before, but I couldn't find anything except people being very confused about what they are doing wrong. :man_shrugging: 
---

add explicit test command?

---

exercises/practice/hello-world/.docs/instructions.append.md

Replaced Mac OS X and OS X with macOS. Also added a link to homebrew's website, should a learner not be familiar with homebrew.
---

updated macOS reference.

---

docs/TESTS.md

Also reformats the markdown style

add link to exercism CLI

---

exercises/practice/error-handling/.docs/instructions.append.md
exercises/practice/error-handling/.docs/instructions.md

The only way to complete this exercise right now is to read tests. PR adds bare bones instructions on what is required
Fixes: #564 
---

Update instructions for error handling in bash

---

exercises/practice/error-handling/.docs/instructions.append.md

Continuation of https://github.com/exercism/bash/pull/576 based on https://github.com/exercism/bash/pull/576#issuecomment-1125214011
---

Fix minor spelling error

---

exercises/practice/hello-world/.docs/instructions.append.md

Hi! Thanks for putting this together! This updates the instructions to help install `bats` on Debian flavored machines. Hope this helps! Thanks again!
---

Add instructions for Debian flavors

---

bin/validate_one_exercise
exercises/practice/list-ops/list_ops.bats

Bringing in some learning from the awk track.
closes #583

Validate tests files have expected number of commented-out skips

---

exercises/practice/luhn/.meta/tests.toml
exercises/practice/luhn/luhn.bats
exercises/practice/rectangles/.meta/tests.toml
exercises/practice/rectangles/rectangles.bats
exercises/practice/roman-numerals/.docs/instructions.md

- update instructions for roman-numerals
- new tests for luhn and rectangles.

Configlet sync

---

exercises/practice/dnd-character/.meta/example.sh
exercises/practice/dnd-character/dnd_character.bats

dnd-character: test hitpoints value exactly

---

exercises/practice/darts/.docs/instructions.append.md
exercises/practice/grep/.docs/instructions.append.md
exercises/practice/hello-world/.docs/instructions.append.md
exercises/practice/list-ops/.docs/instructions.append.md

Add dummy headers for instructions.append.md files

---

exercises/practice/atbash-cipher/.docs/instructions.md
exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/roman_numerals.bats
exercises/practice/series/.meta/tests.toml
exercises/practice/series/series.bats
exercises/practice/triangle/.meta/tests.toml
exercises/practice/triangle/triangle.bats
exercises/practice/variable-length-quantity/.docs/instructions.md
exercises/practice/word-count/.docs/instructions.md

Exercise updates

---

exercises/practice/two-fer/.approaches/introduction.md

Fix typos in introduction.md

---

docs/TESTS.md

docs: Fix typo in docs/TESTS.md

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/bob/.docs/instructions.md
exercises/practice/bob/.docs/introduction.md
exercises/practice/bowling/.docs/instructions.md
exercises/practice/crypto-square/.docs/instructions.md
exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/grep/.docs/instructions.md
exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/matching-brackets/.docs/instructions.md
exercises/practice/meetup/.docs/instructions.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/poker/.meta/config.json
exercises/practice/resistor-color-trio/.docs/instructions.md
exercises/practice/say/.docs/instructions.md
exercises/practice/sieve/.docs/instructions.md
exercises/practice/simple-cipher/.docs/instructions.md
exercises/practice/space-age/.docs/instructions.md
exercises/practice/spiral-matrix/.meta/config.json
exercises/practice/two-fer/.docs/instructions.md

just the configlet sync, no human intervention

Sync docs and metadata

---

exercises/practice/palindrome-products/.meta/tests.toml
exercises/practice/palindrome-products/palindrome_products.bats
exercises/practice/phone-number/.meta/tests.toml
exercises/practice/resistor-color-trio/.meta/tests.toml
exercises/practice/resistor-color-trio/resistor_color_trio.bats

syncing tests.
* phone-number does not use "prescribed" error messages, so just update tests.toml
* resistor-color-trio already had the new tests.

Sync tests

---

exercises/practice/two-fer/.approaches/introduction.md

paramter => parameter
prefered => preferred
---

[Two Fer, Dig Deeper] Two typos

---

exercises/practice/queen-attack/.docs/instructions.md

Doing a round of `configlet sync`s

recent doc updates

---

config.json

Add key features to track bash
resolve #469
---

add key features to track bash

---

exercises/practice/anagram/.meta/tests.toml
exercises/practice/meetup/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/reverse-string/.meta/tests.toml

Sync with problem specs

---

config.json
exercises/practice/reverse-string/.approaches/config.json
exercises/practice/two-fer/.approaches/config.json

`configlet fmt` picked up a couple of exercise configs to touch.
Closes #665

Forego some exercises

---

exercises/practice/all-your-base/.docs/instructions.md
exercises/practice/all-your-base/.docs/introduction.md
exercises/practice/dnd-character/.docs/instructions.md
exercises/practice/dnd-character/.docs/introduction.md
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/roman_numerals.bats
exercises/practice/scrabble-score/.docs/instructions.md
exercises/practice/scrabble-score/.docs/introduction.md

Docs and a new roman-numerals test

Sync recent prob-spec changes

---

exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/poker/.docs/instructions.md
exercises/practice/protein-translation/.meta/tests.toml
exercises/practice/protein-translation/protein_translation.bats
exercises/practice/resistor-color-duo/.docs/instructions.md
exercises/practice/yacht/.meta/config.json

Add new test case which @barabo added to the problem specs.
Sync docs and metadata.

Sync new protein translation test case; sync docs and metadata

---

.github/workflows/ci.yml
.github/workflows/pr.yml

This gets us to bats v1.10
Ref exercism/awk#278

bump workflows to use ubuntu 24.04

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/hamming/.docs/instructions.md
exercises/practice/luhn/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/introduction.md

It's just the docs that have been updated

sync recent problem-spec changes

---

concepts/conditionals/.meta/config.json
concepts/conditionals/about.md
concepts/conditionals/introduction.md
concepts/conditionals/links.json
config.json

I've been kind of agonizing over this one for a few weeks: how much detail to include/omit.

Concept: Conditionals

---

concepts/functions/about.md
concepts/functions/introduction.md

https://exercism.org/tracks/bash/concepts/functions
```none
This example is adapted from the [Shell Functions][man-funcs] section of the manual:
```

Functions concept: fix broken link in admonition block

---

config.json
exercises/practice/beer-song/.deprecated
exercises/practice/bottle-song/.docs/instructions.md
exercises/practice/bottle-song/.meta/config.json
exercises/practice/bottle-song/.meta/example.sh
exercises/practice/bottle-song/.meta/tests.toml
exercises/practice/bottle-song/bats-extra.bash
exercises/practice/bottle-song/bottle_song.bats
exercises/practice/bottle-song/bottle_song.sh

Beer song is deprecated. Replace with bottle song.

Replace beer song with bottle song

---

config.json
exercises/practice/resistor-color/.docs/instructions.md
exercises/practice/resistor-color/.meta/config.json
exercises/practice/resistor-color/.meta/example.sh
exercises/practice/resistor-color/.meta/tests.toml
exercises/practice/resistor-color/bats-extra.bash
exercises/practice/resistor-color/resistor_color.bats
exercises/practice/resistor-color/resistor_color.sh

Forum thread: http://forum.exercism.org/t/exercise-docs-refer-to-another-exercise-that-might-not-be-implemented/15638/4

Resistor color

---

docs/LEARNING.md
docs/RESOURCES.md

An earlier archived version seems more complete.

update bash-hackers.org links from archive.org

---

docs/SYLLABUS.md
docs/config.json

Adds a Syllabus doc to the track docs.

Add links to concept docs to track docs.
