- config.json
The API now handles looking at the new key, so we can remove the old one.
> Remove deprecated 'problems' key from config

- .travis.yml
We will be adding subcommands to configlet.
For now, we've released a version of configlet which handles both the
old command:
configlet path/to/track
as well as the new command:
configlet lint path/to/track
This will let us update all the travis files to include the subcommand before we release the version of configlet that requires the subcommand.
See https://github.com/exercism/configlet/pull/23
> Support a subcommand on configlet in CI

- config/exercise_readme.go.tmpl
- exercises/anagram/README.md
- exercises/bob/README.md
- exercises/difference-of-squares/README.md
- exercises/gigasecond/README.md
- exercises/hamming/README.md
- exercises/hello-world/README.md
- exercises/leap/README.md
- exercises/pangram/README.md
- exercises/phone-number/README.md
- exercises/raindrops/README.md
- exercises/rna-transcription/README.md
- exercises/two-fer/README.md
- exercises/word-count/README.md
We are working towards making exercises stand-alone.
That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise
README, and it will also make some of the backend logic for delivering
exercises simpler.
The README template uses the Go text/template package, and the default
templates generate the same READMEs as we have been generating on the fly.
See the documentation in [regenerating exercise readmes][regenerate-docs] for
details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
Tracking progress of all tracks in: …
> Generate exercise READMEs from templates

- exercises/bob/bob_test.sh
- exercises/bob/example.sh
Fix for https://github.com/exercism/xbash/issues/27
[[:space:]] does not match \u00a0 on linux.
I commented out the test and added a comment for now.
Also DRYed up the code a bit.
> Fix bob bug: [[:space:]] does not match \u00a0 (on linux)

- config.json
When validating UUIDs for all tracks I found that the exercise `error-handling` had a small typo for the uuid key.
> config.json: Fix uuid key for error-handling exercise

- config.json
- exercises/nucleotide-count/README.md
- exercises/nucleotide-count/example.sh
- exercises/nucleotide-count/nucleotide_count_test.sh
I did my best to choose topics and a difficulty for the exercise. The only last two things are should it be a core exercise? If not, what should it be unlocked by?
> implement exercise nucleotide-count

- README.md
Points users to the new contributing document provided in #96 as opposed to the generic `xapi` contributing document.
> fix link to new contributing.md

- docs/MAINTAINING.md
Add markdown to describe the duties of maintaining a repo.
This is heavily influenced by the Java track's document, as I think it is a great example.
> add MAINTAINING.md doc

- exercises/error-handling/README.md
Looks like `error-handling` didn't have a README, so I've generated one.
As the [`metadata.yml`](https://github.com/exercism/problem-specifications/blob/master/exercises/error-handling/metadata.yml) doesn't have a source, I've omitted that section.
> error-handling: add readme

- CONTRIBUTING.md
I've removed the `json` identifier from the json code block in `CONTRIBUTING.md`, as it was being highlighted in red (invalid) as json does not support comments.
Personally, I think this is slightly ugly looking, and as it isn't *really* json, I think it is an improvement to remove the red highlighting.
Let me know what the rest of you think and if this is seen as an improvement we can merge it :slightly_smiling_face:
> fix contributing highlighting 'invalid' json

- CONTRIBUTING.md
- _template/README.md
- _template/example.sh
- _template/exercise_slug_test.sh
Adds a `_template` directory with a basic exercise outline, to facilitate more uniform contributions.
> _template: add a template for quickly porting exercises to track

- README.md
I thought it would be a good idea to add the Travis build badge in order to show visitors the state of our master branch at present.
Looks like most other tracks do the same thing.
> readme: add travis build badge

- CONTRIBUTING.md
Check for actual return value instead of bash exit code.
> Add test output check suggestion

- exercises/error-handling/error_handling_test.sh
- exercises/error-handling/example.sh
The current test "works" when you run it from the CLI in the sense that it does not error, but it does not correctly makes the test pass.
Changes:
- Apply style guide
- Do not check for -e and -u options, since they are suggestions (and mostly because there is not a proper way to test them with bats)
- Add test for output banner, since it's pretty much required for scripts, and IMO it's better than having the script fail with obscure message (unbound variable)
> [error-handling] Fix tests to be CI friendly

- scripts/canonical_data_check.sh
As part of #136, in order to keep test suites up to date, an automated canonical data checker would be useful.
This script checks each exercise for a file at `.meta/version`, and compares the version stored against the relevant canonical data in a local clone of problem-specifications. If a test suite needs updating, it will tell the user.
Currently, all exercises need version files.
> canonical_data_check: add version check script to bash track

- config.json
Massive `config.json` overhaul!
Quick review:
* exercises are listed in difficulty order, and then by alphabetical order
* reviewed difficulty - most exercises were 1 or 2, but this isn't reflective (in my opinion) of the exercises
* add/remove topics as appropriate (and per many open issues) and alphabetise them accordingly
* added a couple more core exercises (luhn, two-fer etc.) to more evenly distribute exercise unlock
Fixes #61, #62, #63, #64, #65, #66, #67, #68, #69, #70, #71, #72, #73, #74, #75, #103, and #109
> config.json: review exercise difficulty/unlocks/ordering

- config.json
The website (http://exercism.io/languages/bash/exercises), presents the exercises in the order they are in the config.json file and the current order is not correct.
> Fix exercise order

- config.json
While linting with the next release of [Configlet](https://github.com/exercism/configlet/releases/tag/v3.8.0) a number of exercises were still found to contain invalid unlocked_by configurations.
The master config file was updated in the following manner:
1. Any exercise containing the unlocked_by value of `"null"` was updated with a null value.
1.Download the pre-release of Configlet [here](https://github.com/exercism/configlet/releases/tag/v3.8.0)
1.Run `configlet lint <path-to-track>`
1.Validate that there are no lint errors.
closes #164
> config.json: Fix unlocked_by errors being reported by Configlet

- exercises/luhn/luhn_test.sh
Since my last PR revealed that the version should not be represented in the test file I checked which ones have it from my templates. It appears that it was only in the luhn exercise.
This PR fixes that.
---
> removed 'version' line from luhn test

- exercises/hello-world/README.md
Line 26 of README.md reads "verions"  instead of "versions." 
Obviously, this is a major issue that will cause bash newbies to be thrown off completely.
I have now fixed this, so you can all rest easy again.
---
> Fix typo in hello world README.md

- exercises/hamming/example.sh
- exercises/hamming/hamming_test.sh
@kotp and I had a discussion regarding the inaccuracy of:
'<*string*1> <*string*2>' in `Usage: <string1> <string2>`
I changed it to `Usage: <strand1> <strand2>` so it would better fit the context.
This change uses the input names from the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/hamming/canonical-data.json) for hamming.
---
> Hamming: changed string to strand in hamming_test.sh and example.sh

- README.md
Exercism now uses the official logo: https://github.com/odb/official-bash-logo
> Remove obsolete information from readme

- exercises/armstrong-numbers/armstrong_numbers_test.sh
- exercises/armstrong-numbers/example.sh
Applies the consistent exit codes rule discussed in the #241 (Although it seems that only `armstrong-numbers` broke them).
Closes #241 
---
> armstrong-numbers: Replaced return status '1' with '0' for tests that expect false result

- exercises/bob/bob_test.sh
Currently the tests send "\n" and "\t" to test talking to Bob with only whitespace.  A student brought it up that they probably should be sending actual, expanded tabs and newlines.  Using `$'dollar single quotes'` allows Bash to expand the escape codes before sending them to `bob.sh`.  (Generally, using `echo` does this for us, but we're running 
```bash
$ bash bob.sh "\n\t\r"
```
not using `echo` so they don't get expanded.)
Bonus: this lets students use the `[[:space:]]` character class in their solutions, which is nice and clean.
---
> Update bob_test.sh: improve ambiguous whitespace tests

- exercises/acronym/example.sh
Change quotes to get correct instructional message e.g. "Usage: ./acronym.sh '<phrase>', 
instead of "Usage: $0 <phrase>"
---
> acronym: change quotes

- exercises/error-handling/error_handling_test.sh
Since a null user should work and produce `Hello, ` as output, adding a test for it would make the implementation clearer.
I didn't find any `canonical-data.json` for the error-handling problem specification, so I added the test directly to the `error_handling_test.sh` file.
---
> Mentor rpalo suggested a null user should work

- config.json
Current difficulties, sorted: http://ix.io/1Kwq
5: atbash-cipher
5: diffie-hellman
5: food-chain
5: grep
5: say
6: affine-cipher
6: two-bucket
8: forth
9: change
Based on my experience/solutions, this change updates the last three:
7: forth
8: change
9: two-bucket
---
> Adjust exercise difficulty for [forth, change, two-bucket]

- bin/validate_exercises
So, I called the validate_exercises script, trying to see why the build is failing.
I did not have an "exercises_temp" directory: the `cd` failed, and the script delete my local "bash" repo.
sad face
Here's a safer version, using `mktemp` to create the tempdir. If you don't want to do that, at the very least add `mkdir -p "$temp_folder"` before trying to cd to it.
* The "cleanup" function is just my style, to make the `trap` call tidier.
* Using `ln` instead of `cp` will speed things up by a few milliseconds.
---
> update validation script for safety

- _template/exercise_slug_test.sh
- exercises/affine-cipher/affine_cipher_test.sh
- exercises/anagram/anagram_test.sh
- exercises/armstrong-numbers/armstrong_numbers_test.sh
- exercises/atbash-cipher/atbash_cipher_test.sh
- exercises/bob/bob_test.sh
- exercises/collatz-conjecture/collatz_conjecture_test.sh
- exercises/diamond/diamond_test.sh
- exercises/difference-of-squares/difference_of_squares_test.sh
- exercises/error-handling/error_handling_test.sh
- exercises/gigasecond/gigasecond_test.sh
- exercises/grains/grains_test.sh
- exercises/hamming/hamming_test.sh
- exercises/hello-world/hello_world_test.sh
- exercises/isbn-verifier/isbn_verifier_test.sh
- exercises/isogram/isogram_test.sh
- exercises/leap/leap_test.sh
- exercises/luhn/luhn_test.sh
- exercises/nucleotide-count/nucleotide_count_test.sh
- exercises/pangram/pangram_test.sh
- exercises/phone-number/phone_number_test.sh
- exercises/raindrops/raindrops_test.sh
- exercises/reverse-string/reverse_string_test.sh
- exercises/rna-transcription/rna_transcription_test.sh
- exercises/roman-numerals/roman_numerals_test.sh
- exercises/scrabble-score/scrabble_score_test.sh
- exercises/triangle/triangle_test.sh
- exercises/two-fer/two_fer_test.sh
- exercises/word-count/word_count_test.sh
Not a high priority item, but the mix of double brackets and single brackets in the test files has been an irritant.
Besides, the `[` command is not documented to have a `==` operator. I guess bash uses a special case for that under the hood.
---
> use bash double brackets in tests

- exercises/collatz-conjecture/collatz_conjecture_test.sh
- exercises/hamming/hamming_test.sh
- exercises/knapsack/knapsack_test.sh
- exercises/scrabble-score/scrabble_score_test.sh
I was reviewing a solution where the student was outputting an empty string, but the `[[ $output -eq 0 ]]` test was passing. My recent fix to use double brackets introduced this regression:
```
$ output=""
$ [ "$output" -eq 0 ] && echo y || echo n
bash: [: : integer expression expected
n
$ [[ $output -eq 0 ]] && echo y || echo n
y
$ [[ $output == "0" ]] && echo y || echo n
n
```
This fix updates all uses of `[[ $output -eq some_number ]]`
---
> We should be doing string matching for output tests, not numeric

- exercises/hamming/example.sh
- exercises/hamming/hamming_test.sh
This change consolidates the different error messages into 1 while still keeping all the test scenarios.
Looking at the history of the canonical-data, there was an edge case for recursive solutions in Haskell where left/right empty input was not picked up. They chose to use specific error messages for these situations.
They don't really add any value for learning bash.
---
> Hamming: streamline error messages

- exercises/diffie-hellman/diffie_hellman_test.sh
unnecessary and unused associative array declaration in test file gives error for older bash.
---
> diffie-helman: bash 3.2 error in test file

- exercises/simple-cipher/simple_cipher_test.sh
Running with bats-core and bash 3.2, the extended pattern in the first test errored.
---
> simple-cipher: issue with extglob in test file

- exercises/resistor-color-trio/resistor_color_trio_test.sh
A couple of extra tests to force solutions to handle awkward input.
---
> resistor-color-trio: tests for invalid octal, extra colors

- docs/TESTS.md
Added `bats` install instructions for windows under Cygwin / MINGW64
---
> Added bats install instructions for windows / cygwin

- docs/TESTS.md
Mac *only* change to demonstrate installing bats-core with homebrew. Ubuntu instructions untouched. 
---
> Update bats-core installation via homebrew on OS X

- docs/TESTS.md
Since on Ubuntu, the `bats` package is the old sstephenson one.
---
> Update steps for Linux to install bats-core from source

- exercises/error-handling/error_handling_test.sh
- exercises/error-handling/example.sh
I was mentoring a solution that used `echo "Usage: $0 <greetee>"` which
fails the incorrect usage tests "$output" tests. I think the tests need to
be changed to reflect (what I think is) the idiomatic use of "$0" in usage
messages.
---
> Error-handling: usage tests do not reflect how script is invoked

- bin/fetch_configlet
https://exercism-team.slack.com/archives/CAQP7JL3T/p1582614952007300
---
> fetch_configlet: retry if curl request fails

- exercises/affine-cipher/README.md
- exercises/darts/.meta/hints.md
- exercises/darts/README.md
- exercises/isbn-verifier/README.md
- exercises/luhn/README.md
- exercises/raindrops/README.md
- exercises/resistor-color-duo/README.md
- exercises/scrabble-score/README.md
- exercises/space-age/README.md
- exercises/two-bucket/README.md
- exercises/two-fer/README.md
- exercises/variable-length-quantity/README.md
- exercises/word-count/README.md
No major changes. Added a darts hints.md file since I hand-edited the README when the exercise was created.
Initialed by problem spec PR. https://github.com/exercism/problem-specifications/pull/1650
---
> Regenerate README files based on current problem specification descriptions

- exercises/hello-world/.meta/hints.md
- exercises/hello-world/README.md
New less confusing merge request, changing remaining references to link to https://github.com/bats-core/bats-core
We have already been pointing people to the newer version since January, so this change just affects what's shown to people along with the Hello World exercise to match that.
I think that in reality, if they installed Bats from e.g. Ubuntu or Fedora lately, they would already be getting a Bats version 1.1 or newer from `bats-core` since some time, so I don't expect this will lead to any issues.
Closes #438
> Change references for bats to point to bats-core

- bin/fetch_configlet
I thought about putting the `rm -f "$localfile"` into a `trap cleanup EXIT` function, but I figured if there's some failure, it may be worthwhile being able to inspect what actually did get downloaded.
---
> Do something with the return status of the fetch_archive function

- exercises/affine-cipher/example.sh
Remove extraneous checks to determine where to get data: just take parameters.  
Also, simplify the co-prime check as the code comments request.
Addresses issue #457 
---
> Fix affine-cipher CI failures

- exercises/two-bucket/.meta/tests.toml
- exercises/two-bucket/two_bucket_test.sh
The new canonical test cases were in part inspired by the bash-only checks.
Syncing this track as housekeeping.
---
> Sync test cases with canonical data

- exercises/two-fer/example.sh
- exercises/two-fer/two_fer_test.sh
The existing glob test will only produce unusual results if there is a filename ending with a comma. Adding a space to the input will mane the incorrect output more obvious that quotes are missing.
Also, updated the example solution
---
> Two-fer glob test improvement

- exercises/practice/bob/bob_test.sh
Unquoted, these will trigger glob expansion matches
I've seen this several times recently.
---
> bob: add a couple of fiendish tests 

- .github/PULL_REQUEST_TEMPLATE.md
- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
- docs/TESTS.md
- exercises/practice/darts/.docs/instructions.append.md
- exercises/practice/gigasecond/.docs/instructions.append.md
- exercises/practice/grep/.docs/instructions.append.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
> [v3] Update Markdown files to latest spec

- exercises/practice/hello-world/.docs/instructions.append.md
The linked repository and command output mismatched the command shown which might lead to confusion if users miss the bash tests documentation which also points to the correct bats-core install.
---
> Change brew install command to bats-core

- exercises/practice/markdown/.meta/example.sh
- exercises/practice/markdown/.meta/tests.toml
- exercises/practice/markdown/markdown.bats
- exercises/practice/markdown/markdown.sh
Checks headers for h3, h4, h5, and validates that 7 hashes don't generate a h7
Recall that this is a refactoring exercise, so the stub file must pass the test suite.  
Fix was required for example solution too.
> add new Markdown test cases

- exercises/shared/.docs/tests.md
Change path to absolute path for instructions to install bats in HELP.md
---
> fix: absolute path to instructions to install bats

- .gitignore
This removes an entry from gitignore, which is is meant to be used for
project related ignores, things that are generated by the project
itself, rather than personal choices that create artifacts.
---
> Remove non-project related gitignore entry

- docs/TESTS.md
- exercises/shared/.docs/tests.md
Closes #585 
To quote that issue:
> The file https://github.com/exercism/bash/blob/main/exercises/shared/.docs/tests.md is used to construct the HELP.md file that is part of the `exercism download ...` content. It contains a section about what to do with the skip directives.
>
> The file https://github.com/exercism/bash/blob/main/docs/TESTS.md is used for [the online docs](https://exercism.org/docs/tracks/bash/tests)
>
> The Skipped tests section should appear under Testing Locally.
> overriding skips instructions on web docs as well as HELP.md file

- exercises/practice/crypto-square/.meta/tests.toml
- exercises/practice/crypto-square/crypto_square.bats
Sync new test for crypto-square: normalization results in empty plaintext
---
> Sync new test for crypto-square: normalization results in empty plaintext

- exercises/practice/gigasecond/.docs/instructions.append.md
> Append bash-specific instructions to gigasecond

- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/largest_series_product.bats
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
> Sync largest-series-product docs with problem-specifications

- exercises/practice/binary-search/.docs/instructions.md
- exercises/practice/gigasecond/.docs/introduction.md
- exercises/practice/pangram/.docs/introduction.md
- exercises/practice/rational-numbers/.docs/instructions.md
- exercises/practice/rna-transcription/.docs/instructions.md
- exercises/practice/rna-transcription/.docs/introduction.md
- exercises/practice/secret-handshake/.docs/instructions.md
- exercises/practice/sieve/.docs/instructions.md
In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705
> Convert backtick (`) admonition fences to tildes (~)

- exercises/practice/hello-world/.meta/config.json
- exercises/practice/phone-number/.docs/instructions.md
- exercises/practice/poker/.meta/tests.toml
- exercises/practice/poker/poker.bats
- exercises/practice/pop-count/.meta/config.json
> Sync bash from problem specs

- exercises/practice/leap/.approaches/boolean-chain/content.md
- exercises/practice/leap/.approaches/boolean-chain/snippet.txt
- exercises/practice/leap/.approaches/config.json
- exercises/practice/leap/.approaches/external-tools/content.md
- exercises/practice/leap/.approaches/external-tools/snippet.txt
- exercises/practice/leap/.approaches/introduction.md
- exercises/practice/leap/.approaches/ternary-operator/content.md
- exercises/practice/leap/.approaches/ternary-operator/snippet.txt
structure and content largely taken from C# and Racket approaches.
> Add approaches for leap

- exercises/practice/reverse-string/.approaches/config.json
- exercises/practice/reverse-string/.approaches/external-tools/content.md
- exercises/practice/reverse-string/.approaches/external-tools/snippet.txt
- exercises/practice/reverse-string/.approaches/introduction.md
- exercises/practice/reverse-string/.approaches/loops/content.md
- exercises/practice/reverse-string/.approaches/loops/snippet.txt
- exercises/practice/reverse-string/.articles/config.json
- exercises/practice/reverse-string/.articles/performance/content.md
- exercises/practice/reverse-string/.articles/performance/snippet.md
> Approaches for reverse-string

- concepts/README.md
- concepts/commands-and-arguments/.meta/config.json
- concepts/commands-and-arguments/about.md
- concepts/commands-and-arguments/introduction.md
- concepts/commands-and-arguments/links.json
- config.json
The first concept in the syllabus.
> Concept: Commands and Arguments

- concepts/README.md
- concepts/quoting/.meta/config.json
- concepts/quoting/about.md
- concepts/quoting/introduction.md
- concepts/quoting/links.json
- config.json
I'm using [admonitions](https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions) pretty liberally here, so we won't really see exactly how they get rendered until the PR is merged.
>  Concept quoting

- exercises/practice/darts/darts.bats
I was able to pass this exercise using incorrect `[[:digit:]]` regular expression that only checked that an argument includes a number so I've decided to slightly update the test case for a non-numeric argument.
---
> test: update Darts exercise test case

- concepts/README.md
- concepts/functions/.meta/config.json
- concepts/functions/about.md
- concepts/functions/introduction.md
- concepts/functions/links.json
- config.json
> Concept: functions

- exercises/practice/error-handling/.docs/instructions.append.md
This is the 3rd simplest exercise (after Hello World and Two Fer) but it is not clear what are the requirements, which might discourage someone from learning Bash.
Currently the entire description displayed is:
> Instructions
> Implement various kinds of error handling and resource management.
> 
> An important point of programming is how to handle errors and close resources even if errors occur.
> 
> This exercise requires you to handle various errors. Because error handling is rather programming language specific you'll have to refer to the tests for your track to see what's exactly required.
> 
> Bash-specific instructions
> The goal of this exercise is to consider the number of arguments passed to your program. If there is exactly one argument, print a greeting message. Otherwise …
> Improve description of Error Handling exercise

- concepts/commands-and-arguments/about.md
- concepts/commands-and-arguments/introduction.md
- concepts/conditionals/about.md
- concepts/conditionals/introduction.md
- concepts/functions/about.md
- concepts/functions/introduction.md
- concepts/looping/about.md
- concepts/looping/introduction.md
- concepts/pipelines/about.md
- concepts/pipelines/introduction.md
- concepts/quoting/about.md
- concepts/quoting/introduction.md
- concepts/variables/about.md
- concepts/variables/introduction.md
Even though I think they are ignored when rendering the page.
I also forgot to populate the About page for Looping.
> Make top-level headers consistent

- concepts/more-arrays/about.md
- concepts/more-arrays/introduction.md
Some of the comments wrapped to the next line.
> formatting and grammar fixes

- exercises/practice/simple-cipher/simple_cipher.bats
- The last line of the "Can generate a random key" test was incorrect.
- glennj agreed with the proposed change in the exercism community.
---
> Simple Cipher: Corrected a test.

- concepts/README.md
- concepts/heredocs/.meta/config.json
- concepts/heredocs/about.md
- concepts/heredocs/introduction.md
- concepts/heredocs/links.json
- config.json
- docs/SYLLABUS.md
Next concept: here documents and here strings.
> Concept: Here Documents

- config.json
```
jq '.exercises.practice = (.exercises.practice|sort_by(.difficulty, .slug))' config.json > t && mv t config.json
```
> Sort practice exercises by difficulty then slug.

- config.json
- exercises/practice/flower-field/.docs/hints.md
- exercises/practice/flower-field/.docs/instructions.md
- exercises/practice/flower-field/.docs/introduction.md
- exercises/practice/flower-field/.meta/config.json
- exercises/practice/flower-field/.meta/example.sh
- exercises/practice/flower-field/.meta/tests.toml
- exercises/practice/flower-field/bats-extra.bash
- exercises/practice/flower-field/flower_field.bats
- exercises/practice/flower-field/flower_field.sh
[Forum thread](https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967) discussing the change
> Replace Minesweeper with Flower Field
